CREATE USER manohar WITH PASSWORD 'YourStrongPassword123';

GRANT CONNECT ON DATABASE theinstacloset TO manohar;

GRANT USAGE ON SCHEMA public TO manohar;

GRANT SELECT, INSERT, UPDATE, DELETE
ON ALL TABLES IN SCHEMA public
TO manohar;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT SELECT, INSERT, UPDATE, DELETE
ON TABLES TO manohar;
