flyway.url=jdbc:postgresql://theinstacloset-postgres.xxxxx.ap-south-1.rds.amazonaws.com:5432/theinstacloset

flyway.user=insta

flyway.password=Bathula147!

flyway.locations=filesystem:sql/theinstacloset
